# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AchiDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for AchiDemo
  pod 'TKSwitcherCollection'

  target 'AchiDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'BoardGameContainerFramework' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoardGameContainerFramework

end
